# References
# https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references
# https://en.wikipedia.org/wiki/Help:Displaying_a_formula
# https://www.unicode.org/charts/nameslist/n_2200.html

[general]
# HTML Character Entities
ndash  = 'â€“'
mdash  = 'â€”'
horbar = 'â€•' # Horizontal Bar (U+2015), quotation dash
middot = 'Â·' # Middle Dot (U+00B7)
bullet = 'â€¢' # Bullet (U+2022)
laquo  = 'Â«'
raquo  = 'Â»'
cross  = 'â¨¯' # Vector Or Cross Product (U+2A2F)
check  = 'âœ“' # Check Mark (U+2713)

# Custom
mdot     = 'Â·' # Middle Dot (U+00B7)
bulletop = 'âˆ™' # Bullet Operator (U+2219)
degc     = 'â„ƒ'
lcb      = 'ã€Œ' # Left Corner Bracket (U+300C)
rcb      = 'ã€' # Right Corner Bracket (U+300D)
lwcb     = 'ã€Ž' # Left White Corner Bracket (U+300E)
rwcb     = 'ã€' # Right White Corner Bracket (U+300F)

heavycheck      = 'âœ”' # Heavy Check Mark (U+2714)
heavymul        = 'âœ–' # Heavy Multiplication X (U+2716)
ballotbox       = 'â˜' # Ballot Box (U+2610)
ballotcheck     = 'â˜‘' # Ballot Box With Check (U+2611)
ballotboldcheck = 'ðŸ—¹' # Ballot Box With Bold Check (U+1F5F9)

square      = 'â–¡'
blacksquare = 'â– '
triangle    = 'â–³'
dtriangle   = 'â–½'
ltriangle   = 'â—ƒ'
rtriangle   = 'â–¹'

[subscript_superscript]
sup0   = 'â°'
sup1   = 'Â¹'
sup2   = 'Â²'
sup3   = 'Â³'
sup4   = 'â´'
sup5   = 'âµ'
sup6   = 'â¶'
sup7   = 'â·'
sup8   = 'â¸'
sup9   = 'â¹'
'sup+' = 'âº'
'sup-' = 'â»'
'sup(' = 'â½'
'sup)' = 'â¾'

sub0   = 'â°'
sub1   = 'â‚'
sub2   = 'â‚‚'
sub3   = 'â‚ƒ'
sub4   = 'â‚„'
sub5   = 'â‚…'
sub6   = 'â‚†'
sub7   = 'â‚‡'
sub8   = 'â‚ˆ'
sub9   = 'â‚‰'
'sub+' = 'â‚Š'
'sub-' = 'â‚‹'
'sub(' = 'â‚'
'sub)' = 'â‚Ž'

[greek]
alpha   = 'Î±'
beta    = 'Î²'
gamma   = 'Î³'
delta   = 'Î´'
epsilo  = 'Îµ'
zeta    = 'Î¶'
eta     = 'Î·'
theta   = 'Î¸'
iota    = 'Î¹'
kappa   = 'Îº'
lambda  = 'Î»'
mu      = 'Î¼'
nu      = 'Î½'
xi      = 'Î¾'
omicron = 'Î¿'
pi      = 'Ï€'
rho     = 'Ï'
sigma   = 'Ïƒ'
tau     = 'Ï„'
upsilon = 'Ï…'
phi     = 'Ï†'
chi     = 'Ï‡'
psi     = 'Ïˆ'
omega   = 'Ï‰'

Alpha   = 'Î‘'
Beta    = 'Î’'
Gamma   = 'Î“'
Delta   = 'Î”'
Epsilo  = 'Î•'
Zeta    = 'Î–'
Eta     = 'Î—'
Theta   = 'Î˜'
Iota    = 'Î™'
Kappa   = 'Îš'
Lambda  = 'Î›'
Mu      = 'Îœ'
Nu      = 'N'
Xi      = 'X'
Omicron = 'ÎŸ'
Pi      = 'Î '
Rho     = 'Î¡'
Sigma   = 'Î£'
Tau     = 'Î¤'
Upsilon = 'Î¥'
Phi     = 'Î¦'
Chi     = 'Î§'
Psi     = 'Î¨'
Omega   = 'Î©'

varepsilon = 'Îµ'
varkapa    = 'Ï°'
varphi     = 'Ï†'
varpi      = 'Ï–'
varrho     = 'Ï±'
varsigma   = 'Ï‚'
vartheta   = 'Ï‘'

[arrow]
uarr = 'â†‘'
darr = 'â†“'
rarr = 'â†’'
larr = 'â†'
varr = 'â†•'
harr = 'â†”'

Uarr = 'â‡‘'
Darr = 'â‡“'
Rarr = 'â‡’'
Larr = 'â‡'
Varr = 'â‡•'
Harr = 'â‡”'

dashrarr   = 'â‡¢'
dashlarr   = 'â‡ '
lrarr      = 'â‡†'
rlarr      = 'â‡„'
lrharpoons = 'â‡‹'
rlharpoons = 'â‡Œ'

nearr = 'â†—'
nwarr = 'â†–'
searr = 'â†˜'
swarr = 'â†™'

ccwarr = 'â†º'
cwarr  = 'â†»'

[latex]
times    = 'Ã—' # Multiplication Sign (U+00D7)
pm       = 'Â±'
neq      = 'â‰ '
approx   = 'â‰ˆ'
approxeq = 'â‰Š'
simeq    = 'â‰ƒ'
cong     = 'â‰…'
ge       = 'â‰¥'
gt       = '>'
gg       = 'â‰«'
le       = 'â‰¤'
lt       = '<'
ll       = 'â‰ª'
iif      = 'âŸº'

nabla   = 'âˆ‡'
partial = 'âˆ‚'
ell     = 'â„“'
sum     = 'âˆ‘'
prod    = 'âˆ'
int     = 'âˆ«'
forall  = 'âˆ€'
exist   = 'âˆƒ'
infin   = 'âˆž'
propto  = 'âˆ'
degree  = 'Â°'

in       = 'âˆˆ'
notin    = 'âˆ‰'
ni       = 'âˆ‹'
cap      = 'âˆ©'
cup      = 'âˆª'
subset   = 'âŠ‚'
subseteq = 'âŠ†'
supset   = 'âŠƒ'
supseteq = 'âŠ‡'

cdot  = 'â‹…' # Dot Operator (U+22C5)
ldots = 'â€¦'
cdots = 'â‹¯'
vdots = 'â‹®'
ddots = 'â‹±'
circ  = 'âˆ˜' # Ring Operator (U+2218)

[etc]
shrug = 'Â¯\_(ãƒ„)_/Â¯'
